---
title: My Resume
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://webjeda.com
baseurl: "/online-cv"
name: Alan Doe
tagline: Full Stack Developer
pic: profile.png
email: hello@webjeda.com
phone: 012 345 6789
website: blog.webjeda.com
linkedin: alandoe
github: sharu725
twitter: "@webjeda"
