---
title: My Resume
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://ericslin.com
baseurl: ''
name: Eric Sihao Lin
tagline: Currently coding as a hobby
pic: profile.jpg
email: eric.lin@nyu.edu
website: ericslin.com
linkedin: ericsihaolin
github: mainlandhero
twitter: "@ericslin"
